### ISSUE TITLE
MAC should scan the client for cheat software.

### ISSUE THREAD

**Issue by dyeddaboi** [MegaAntiCheat/client-backend#12]
This is for obvious reasons
If a cheater decides to install this knowingly they should get what's coming to them lol

**Comment by lili7h** [comment]
No, we are not creating a software that scans or otherwise looks through your computer. The only files we ever access are demos and the console log, as well as our own config files. 

This would just add bloat to a software that would only harm non-cheaters because cheaters will never voluntarily install an anti-cheat
