### ISSUE TITLE
Could not locate loginusers.vdf in the Steam dir, even when the tf2 directory is specified and the file exists in that larger steam directory.

### ISSUE THREAD

**Issue by TehDrpStr** [MegaAntiCheat/client-backend#121]
Linux mint 21.3, trying to run 'cargo run -- --tf2-dir "/home/titan/.steam/debian-installation/steamapps/common/Team Fortress 2"' gives that error. I'm logged in and have steam running. Everything else runs as expected.

**Comment by Bash-09** [comment]
The instances of this issues I've seen pop up tend to be because of leftover files when switching to the native steam install instead of the flatpak one. If anyone experiencing this issue previously had the flatpak version of steam installed but since removed it, deleting the steam folder in `~/.var/app/` has worked for people.

**Comment by Bash-09** [comment]
A workaround for this has been added in #158 
The recommended solution if anybody encounters this issue is to specify both the TF2 directory and their steam user by running the client with the following arguments:
`--tf2-dir path_to_TF2_directory --steam-user 7565.....`
