### ISSUE TITLE
client-backend/ui/ Empty

### ISSUE THREAD

**Issue by ve-cto** [MegaAntiCheat/client-backend#143]
`client-backend/ui/` is completely empty and has no current purpose since the ui is being handled by ./MegaAntiCheat-UI/ 
 ([https://github.com/MegaAntiCheat/MegaAntiCheat-UI](url))

**Comment by Bash-09** [comment]
The `ui` folder is compiled into the binary and anything inside it, so users can provide their own web-based frontend if they like. Since #138 I don't think it's strictly necessary for the client to build anymore, but removing it would also require adjustments to the include UI scripts and having it there is more explicit it anybody did want to add their own UI. So yes, it is empty but that is intentional.
