### ISSUE TITLE
Casual TF2: "Player Lost Connection" but persists in MAC 

### ISSUE THREAD

**Issue by megascatterbomb** [MegaAntiCheat/client-backend#46]
When a player disconnects in a way that results in "Player Lost Connection", MAC still thinks they're in game.

This is technically a bug, but with proper support I think it would be useful to persist players who have recently disconnected for some time (say a couple minutes), but indicate they have disconnected somehow.

![image](https://github.com/MegaAntiCheat/client-backend/assets/55725012/ce98d2b0-bb2d-4d32-8b88-818641596175)
![20230815142246_1](https://github.com/MegaAntiCheat/client-backend/assets/55725012/d60db24f-dd5f-48bd-87ae-6b484ed8fe75)

**Comment by Bash-09** [comment]
I will have to investigate how the player shows up in the `status` and `g15` commands. 

Players who stop showing up in those commands automatically get pruned from the serverlist after several seconds, but if they persist beyond that they may still appear as present according to the commands so I'm not 100% sure at this point in time if there's a way to distinguish this.

**Comment by megascatterbomb** [comment]
My guess (I haven't investigated) is `tf_lobby_debug` is responsible as "Player Lost Connection" means the player's slot is reserved for a few minutes, giving them time to get back in the game. Since they're technically still allocated to the lobby, the backend may be seeing them in the command output and thus assuming they're still ingame.

**Comment by Bash-09** [comment]
The `tf_lobby_debug` command is not being used anymore.

**Comment by THE-EXP** [comment]
Speculation:
If the Player leaves for an unexpected reason(i.e. game crashed, internet dropped out, some error occured on the client or anything else(except manual disconnection and being vote-kicked) the slot will be reserved to the player so that they can get back into the game(the "Your Match is ready" popup at the top-center of the screen), so as long as the player doesn't disconnect manually or abandon the match after they suddenly disconnect, the slot will be reserved for them for ~30s-1min, i don't know the actual number, but it seems to be as such

**Comment by lili7h** [comment]
Yeah I believe as long as the scoreboard doesn't detail a slot as "Looking for player..." and instead as something like "Player joining..." or "Player lost connection...", the `g15.m_bValid[<id>]` value will remain true as that players data may still be relevant when they resume connection. A simple fix may be to change the predicate under which we keep entities in the `g15` list. Perhaps instead of looking for `g15.m_bValid[<id>] -> true` we could look for something like `g15.m_bConnected[<id>] -> true` but that may sport the same issues (and wont pull in players that are currently joining but not ingame yet)

**Comment by lili7h** [comment]
stale.
